#include "CoreMemorySpawnFragmentOnEventWithinRangeOfTargetBehaviour.h"

UCoreMemorySpawnFragmentOnEventWithinRangeOfTargetBehaviour::UCoreMemorySpawnFragmentOnEventWithinRangeOfTargetBehaviour()
{
	this->_tileSpawnPointType = ETileSpawnPointType::Unspecified;
}
