#pragma once

#include "CoreMinimal.h"
#include "EInputInteractionType.generated.h"

UENUM(BlueprintType)
enum class EInputInteractionType : uint8
{
	VE_None,
	VE_Interact,
	VE_ItemUse,
	VE_FastInteract,
	VE_AttackInteract,
	VE_ItemInteract,
	VE_Rush,
	VE_AbilityUse,
	VE_ActivatablePerk01,
	VE_ActivatablePerk02,
	VE_ActivatablePerk03,
	VE_ActivatablePerk04,
	VE_Run,
	VE_ItemDrop,
	VE_InteractMash,
	VE_Struggle,
	VE_AbilityTwo,
	VE_EventAbility,
	VE_Action,
	VE_Crouch,
	VE_ActionKiller,
	VE_CancelCharge,
	VE_WiggleLeft,
	VE_WiggleRight,
	VE_SecondaryAction,
	VE_Gesture01,
	VE_Gesture02,
	VE_Gesture03,
	VE_Gesture04,
	VE_ExternalChainBlink,
	VE_ExternalRequestClosetExitFast,
	VE_ExternalRequestClosetStun,
	VE_ExternalRequestDestroyWithPowerAttack,
	VE_ExternalRequestDrop,
	VE_ExternalRequestDropBySkillCheck,
	VE_ExternalRequestDropByStunning,
	VE_ExternalRequestDropByStunningWithFlashlight,
	VE_ExternalRequestDropByStunningByPallet,
	VE_ExternalRequestDropByWiggleFree,
	VE_ExternalRequestEscape,
	VE_ExternalRequestFlashlightStunUncloak,
	VE_ExternalRequestGeneratorTrapStun,
	VE_ExternalRequestHalloweenHauntStun,
	VE_ExternalRequestHarpoonRifleStun,
	VE_ExternalRequestKickStun,
	VE_ExternalRequestKillerCaughtInBearTrap,
	VE_ExternalRequestPalletStun,
	VE_ExternalRequestPalletStunUncloak,
	VE_ExternalRequestPutToSleepStun,
	VE_ExternalRequestRBTExecute,
	VE_ExternalRequestRBTExecuteAtExit,
	VE_ExternalRequestSacrifice,
	VE_ExternalRequestSlashedOutOfTrap,
	VE_ExternalRequestStun,
	VE_ExternalRequestStunBySkillCheck,
	VE_ExternalRequestStunEvilWithin,
	VE_ExternalRequestStunUncloak,
	VE_ExternalRequestK32TeleportToSurvivor,
	VE_Count,
};
