#include "ProximityToSpawnPointTypeIterativeWeightAdjustmentStrategy.h"

UProximityToSpawnPointTypeIterativeWeightAdjustmentStrategy::UProximityToSpawnPointTypeIterativeWeightAdjustmentStrategy()
{
	this->_spawnPointType = ETileSpawnPointType::Unspecified;
}
