#include "K35SurvivorDestroyKillerTeleportPointFailureStunInteractionDefinition.h"

UK35SurvivorDestroyKillerTeleportPointFailureStunInteractionDefinition::UK35SurvivorDestroyKillerTeleportPointFailureStunInteractionDefinition()
{

}
